span class="re0"> common: &common
 vista_db_user: vistasupport

production:
 <<: *common
 environment: production
 bbl_ws_domain: learn-staging.csuchico.edu
 bbl_tool_pass: atec!d1rn
 bbl_registration_pass: pass1234
 bbl_db_table: BBLEARN

staging:
 <<: *common
 environment: staging
 bbl_ws_domain: learn-staging.csuchico.edu
 bbl_tool_pass: atec!d1rn
 bbl_registration_pass: pass1234
 bbl_db_table: BBLEARN

development:
 <<: *common
 environment: development
 bbl_ws_domain: learn-staging.csuchico.edu
 bbl_tool_pass: atec!d1rn
 bbl_registration_pass: pass1234
 bbl_db_table: BBLEARN

