span class="re0"> common: &common
 vista_db_user: vistasupport

production:
 <<: *common
 environment: production
 bbl_ws_domain: learn-staging.csuchico.edu
 bbl_tool_pass: toolpass
 bbl_db_table: BBLEARN
 bbl_vendor_id: CSU_CHICO
 bbl_program_id: CSUC_SS_TOOL
 bbl_emulate_user: @selfservice
 bbl_script_host: bbdev1.csuchico.edu
 bbl_script_user: bbuser
 bbl_script_pass: scriptpass
 bbl_sso_password: ssopassword
 bbl_sso_secret: ssosecret
 bbl_tool_registration_password: regpass
 bbl_tool_registration_secret: 
 selfservice_dsk_pk1: 21

staging:
 <<: *common
 environment: staging
 bbl_ws_domain: learn-staging.csuchico.edu
 bbl_tool_pass: toolpass
 bbl_db_table: BBLEARN
 bbl_vendor_id: CSU_CHICO
 bbl_program_id: CSUC_SS_TOOL
 bbl_emulate_user: @selfservice
 bbl_script_host: bbdev1.csuchico.edu
 bbl_script_user: bbuser
 bbl_script_pass: scriptpass
 bbl_sso_password: ssopassword
 bbl_sso_secret: ssosecret
 bbl_tool_registration_password: regpass
 bbl_tool_registration_secret: 
 selfservice_dsk_pk1: 21

development:
 <<: *common
 environment: development
 bbl_ws_domain: learn-staging.csuchico.edu
 bbl_tool_pass: toolpass
 bbl_db_table: BBLEARN
 bbl_vendor_id: CSU_CHICO
 bbl_program_id: CSUC_SS_TOOL
 bbl_emulate_user: @selfservice
 bbl_script_host: bbdev1.csuchico.edu
 bbl_script_user: bbuser
 bbl_script_pass: scriptpass
 bbl_sso_password: ssopassword
 bbl_sso_secret: ssosecret
 bbl_tool_registration_password: regpass
 bbl_tool_registration_secret: 
 selfservice_dsk_pk1: 21


