development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_development
  pool: 5
  username: dltservice
  password: eMyEZQc4ev5zeBbm
  host: apphostdev.csuchico.edu

staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_development
  pool: 5
  username: dltservice
  password: eMyEZQc4ev5zeBbm
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_production
  pool: 5
  username: dltservice
  password: eMyEZQc4ev5zeBbm
  host: localhost

vista_db:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: stage1.lmsdb2.csuchico.edu
  username: vistasupport
  password: adm1nIZ34

oracle_development:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: bbdev1.lmsdb2.csuchico.edu
  username: learnsupport
  password: adm1nIZ34

oracle_staging:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: bbtest.lmsdb2.csuchico.edu
  username: learnsupport
  password: adm1nIZ34

oracle_production:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: bbtest.lmsdb2.csuchico.edu
  username: learnsupport
  password: adm1nIZ34

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_test
  pool: 5
  username: root
  password: d0gstar2
  host: localhost

