#INFORMATION FOR PRODUCTION AND STAGING MAY NEED TO BE CHANGED

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_bblearn_development
  pool: 5
  username: dltservice
  password: 
  host: apphostdev.csuchico.edu
#  username: root
#  password: 
#  host: localhost

staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_bblearn_development
  pool: 5
  username: dltservice
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_bblearn_production
  pool: 5
  username: dltservice
  password: 
  host: localhost

oracle_development:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: bbdev1.lmsdb2.csuchico.edu
  username: learnsupport
  password:

oracle_staging:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: bbdev1.lmsdb2.csuchico.edu
  username: learnsupport
  password: 

oracle_production:
  adapter: oracle_enhanced
  host: lmsdb2.csuchico.edu
  database: bbdev1.lmsdb2.csuchico.edu
  username: learnsupport
  password:

