# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_development #mbk 101011 fix for local test
  pool: 5
  #username: root
  #password: d0gstar2
  #host: localhost
  username: dltservice
  password: eMyEZQc4ev5zeBbm
  host: apphostdev.csuchico.edu

staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_development
  pool: 5
  username: dltservice
# This password is not used.  This file gets copied over on the staging server
# when cap staging deploy runs.
  password: #########
  host: localhost
   
vista_db:
    adapter: oracle
    database: lmsdb2.csuchico.edu:1521/stage1.lmsdb2.csuchico.edu
    username: vistasupport
    password: adm1nIZ34

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_test 
  pool: 5
  #username: root
  #password: d0gstar2
  #host: localhost
  username: dltservice
  password: eMyEZQc4ev5zeBbm
  host: apphostdev.csuchico.edu

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dlt_vista_production
  pool: 5
  username: dltservice
  password: eMyEZQc4ev5zeBbm
  host: localhost
